[project]
name = "flask-practice"
version = "0.1.0"
description = "MSAI Flask Practice"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "flask>=3.1.0",
    "python-dotenv>=1.1.0",
]
